### ISSUE TITLE
Tripadvisor

### ISSUE THREAD

**Issue by treviser** [blooparksystems/bp_social_media_icon_extention#1]
Thank you for this valuable contribution.
I thought about extending your extension myself in order to include Tripadvisor, but if you would mind to add Tripadvisor the tribute would remain with you. :-)

**Comment by Benniphx** [comment]
Hi, sure I can extend it with Tripadvisor.

**Comment by treviser** [comment]
Cool, thanks!

**Comment by Benniphx** [comment]
I added Tripadvisor :)
best regards Bloopark

**Comment by treviser** [comment]
Thank you!

**Comment by Benniphx** [comment]
@treviser I updated the Add-on, because saw odoo 8 uses a old Font-Awesome 4.0 and the Tripadvisor icon was introduced with Font-Awesome 4.4+ .
