### ISSUE TITLE
Can't load the module

### ISSUE THREAD

**Issue by treviser** [blooparksystems/bp_social_media_icon_extention#2]
Hi Benjamin

I tried to load the module, but I can't. I have uploaded it manually to the server, but it does not show up in the modules list, even if I update the modules list.
When I try to import it, I get the following error message

Error while importing module 'bp_social_media_icon_extention-master': '"ValidateError\nField(s) `arch` failed against a constraint: Invalid view definition\n\nError details:\nField `social_xing` does not exist\n\nError context:\nView `website.form`\n[view_id: 2004, xml_id: n/a, model: website, parent_id: 294]" while parsing /tmp/tmp6r6fto/bp_social_media_icon_extention-master/views/website_views.xml:5, near\n<record id="view_website_form_extra" model="ir.ui.view">\n\t\t\t<field name="name">website.form</field>\n\t\t\t<field name="model">website</field>\n\t\t\t<field name="inherit_id" ref="website.view_website_form"/>\n\t\t\t<field name="arch" type="xml">\n\t\t\t\t<field name="social_github" position="after">\n\t\t\t\t\t<field name="social_xing" placeholder="http://www.xing.com"/>\n\t\t\t\t\t<field name="social_dribbble" placeholder="http://dribbble.com"/>\n\t\t\t\t\t<field name="social_tripadvisor" placeholder="http://tripadvisor.de"/>\n\t\t\t\t</field>\n\t\t\t</field>\n\t\t</record>'

**Comment by Benniphx** [comment]
I just tested it again it works fine here. Did you restart you odoo server to get the Python code loaded ?

**Comment by treviser** [comment]
I don't know, what happened, but it works fine now. Thank you.

**Comment by Benniphx** [comment]
nice to hear :)
